Name:           ros-indigo-object-recognition-capture
Version:        0.3.0
Release:        0%{?dist}
Summary:        ROS object_recognition_capture package

Group:          Development/Libraries
License:        BSD
URL:            http://wg-perception.github.io/capture
Source0:        %{name}-%{version}.tar.gz

Requires:       boost-devel
Requires:       ros-indigo-ecto
Requires:       ros-indigo-ecto-image-pipeline
Requires:       ros-indigo-ecto-opencv
Requires:       ros-indigo-ecto-openni
Requires:       ros-indigo-ecto-ros
Requires:       ros-indigo-object-recognition-core
BuildRequires:  boost-devel
BuildRequires:  ros-indigo-catkin
BuildRequires:  ros-indigo-ecto
BuildRequires:  ros-indigo-ecto-image-pipeline
BuildRequires:  ros-indigo-ecto-opencv
BuildRequires:  ros-indigo-ecto-openni
BuildRequires:  ros-indigo-object-recognition-core

%description
Capture is a set of tools to capture objects in 3D and perform odometry

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p build && cd build
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd build
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Sun Jul 27 2014 Vincent Rabaud <vincent.rabaud@gmail.com> - 0.3.0-0
- Autogenerated by Bloom

